<?php
/**
 * @file
 * Views news carousel.
 */

/**
 * Implements hook_views_api().
 */
function bootsmacss_views_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements template_preprocess_hook().
 */
function template_preprocess_views_view_bootsmacss_listing(&$variables) {
  $view = $variables['view'];
  $rows = $variables['rows'];

  $style_plugin = $view->style_plugin;
  $style_plugin_options = $style_plugin->options;
  $row_plugin = $style_plugin->row_plugin;

  $variables['listing_classes_array'] = [];

  $variables['listing_modifier'] = '';
  if (!empty($style_plugin_options['listing_modifier']) && $style_plugin_options['listing_modifier'] != 'default') {
    $listing_modifiers = $style_plugin_options['listing_modifier'];
    foreach ($listing_modifiers as $listing_modifier_class) {
      $variables['listing_classes_array'][] = 'listing--' . str_replace('_', '-', $listing_modifier_class);
    }
  }

  $variables['listing_modifier_extra'] = '';
  if (!empty($style_plugin_options['listing_modifier_extra'])) {
    $variables['listing_modifier_extra'] = $style_plugin_options['listing_modifier_extra'];
    $variables['listing_classes_array'][] = $variables['listing_modifier_extra'];
  }

  if ($row_plugin->plugin_name == 'ds') {
    $ds_view_mode = $row_plugin->options['view_mode'];
    $variables['ds_view_mode'] = 'listing--' . str_replace('_', '-', $ds_view_mode);
    $variables['listing_classes_array'][] = $variables['ds_view_mode'];
  }

  // Calculating columns and adding modifiers for listing__wrapper based on
  // columns.
  $variables['listing_columns'] = '';
  if (!empty($style_plugin_options['listing_columns']) && $style_plugin_options['listing_columns'] != 'default') {
    $listing_column_name = $style_plugin_options['listing_columns'];
    $variables['listing_columns'] = 'listing--' . str_replace('_', '-', $listing_column_name);
    $variables['listing_classes_array'][] = $variables['listing_columns'];
  }

  $variables['listing_classes'] = implode(' ', $variables['listing_classes_array']);

  $columns_num = 1;
  if (isset($listing_column_name) && $listing_column_name == 'two_columns') {
    $columns_num = 2;
  }
  elseif (isset($listing_column_name) && $listing_column_name == 'three_columns') {
    $columns_num = 3;
  }

  // Distribute items into columns.
  $total = count($rows);
  $variables['columns'] = array();
  $max_items_in_column = array();

  for ($i = 0; $i < $columns_num; $i++) {
    $max_items_in_column[] = floor(($total + $columns_num - ($i + 1)) / $columns_num);
  }

  $counter = 0;
  for ($i = 0; $i < $columns_num; $i++) {
    for ($j = 0; $j < $max_items_in_column[$i]; $j++) {
      $variables['columns'][$i][] = $rows[$counter];
      $counter++;
    }
  }
}
